/**
 * 
 */
package edu.unicen.experimenter;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author esteban
 * 
 */
@Entity
public class DataSetMetaData {
	/**
	 * Entity autogenerated id.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	/**
	 * 
	 */
	public DataSetMetaData() {
		// TODO Auto-generated constructor stub
	}
}
