/**
 * 
 */
package edu.unicen.surfforecaster.server.domain.entity;

import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MapKey;
import javax.persistence.OneToMany;

import org.apache.commons.lang.Validate;

/**
 * Represents a country which contains a set of zones.
 * 
 * @author esteban
 * 
 */
@Entity
public class Country {
	/**
	 * Entity autogenerated id.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	/**
	 * the country name.
	 */
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@MapKey(name = "language")
	private final Map<String, I18nKeyValue> names = new HashMap<String, I18nKeyValue>();

	/**
	 * the zones this country contains.
	 */
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private final Set<Zone> zones = new HashSet<Zone>();

	/**
	 * Empty constructor.
	 */
	public Country() {
		names.put("es", new I18nKeyValue("es", "argentina"));
		// ORM purpose.
	}

	/**
	 * Sets the id.
	 * 
	 * @param id
	 */
	public void setId(final Integer id) {
		this.id = id;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	public void addZone(final Zone theZone) {
		Validate.notNull(theZone, "the zone to be added cannot be null");
		zones.add(theZone);
	}

	public void removeZone(final Zone theZone) {
		Validate.notNull(theZone, "the zone to be removed cannot be null");
		zones.remove(theZone);
	}

	/**
	 * @return the zones
	 */
	public Set<Zone> getZones() {
		return Collections.unmodifiableSet(zones);
	}

	/**
	 * Obtain the country name for the given language.
	 * 
	 * @param language
	 * @return the country name for the given language
	 */
	public String getName(final String language) {
		Validate.notNull(language);
		final I18nKeyValue value = names.get(language);
		if (value != null)
			return value.getText();
		else
			return null;
	}
}
