/**
 * 
 */
package edu.unicen.surfforecaster.server.domain.entity.forecaster;

import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MapKey;
import javax.persistence.OneToMany;

import org.apache.commons.lang.Validate;

import edu.unicen.surfforecaster.common.services.dto.ForecastAttributeDTO;
import edu.unicen.surfforecaster.common.services.dto.ForecastDTO;

/**
 * @author esteban
 * 
 */
@Entity
public class Forecast {
	/**
	 * Entity autogenerated id.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
	/**
	 * The base date of this forecast.
	 */
	private Date baseDate;
	/**
	 * The date to which this forecast applies. This corresponds to Hours since
	 * the baseDate.
	 */
	private Integer forecastTime;
	/**
	 * Map with <attributeName, attributeValue> info. Attributes may be:
	 * waveHeight, wavePeriod, waveDirection, windSpeed.
	 */
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@MapKey(name = "attributeName")
	private Map<String, ForecastAttribute> attributes;

	/**
	 * Default Constructor.
	 */
	public Forecast() {
		// ORM purpose.
	}

	/**
	 * @param baseDate
	 * @param runDate
	 * @param forecastDate
	 * @param attributes
	 * @param ww3Forecaster
	 */
	public Forecast(final Date baseDate, final Integer forecastTime,
			final Map<String, ForecastAttribute> attributes,
			final Forecaster forecaster) {
		Validate.notNull(baseDate);
		Validate.notNull(attributes);
		Validate.notNull(forecaster);
		this.baseDate = baseDate;
		this.forecastTime = forecastTime;
		this.attributes = attributes;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @return the attributes this forecast has.
	 */
	public ForecastAttribute getAttribute(final String attributeName) {
		return attributes.get(attributeName);
	}

	/**
	 * @return the baseDate
	 */
	public Date getBaseDate() {
		return baseDate;
	}

	/**
	 * @return forecastTime which is the hours ahead the baseDate for which this
	 *         forecast belongs.
	 */
	public Integer getForecastTime() {
		return forecastTime;
	}

	/**
	 * @return
	 */
	public ForecastDTO getDTO() {
		final Collection<ForecastAttribute> values = attributes.values();
		final Map<String, ForecastAttributeDTO> map = new HashMap<String, ForecastAttributeDTO>();
		for (final Iterator iterator = values.iterator(); iterator.hasNext();) {
			final ForecastAttribute forecastAttribute = (ForecastAttribute) iterator
					.next();
			map.put(forecastAttribute.getAttributeName(), forecastAttribute
					.getDTO());
		}
		return new ForecastDTO(getBaseDate(), getForecastTime(), map);
	}

	/**
	 * @return
	 */
	public Point getPoint() {
		// TODO Auto-generated method stub
		return null;
	}

}
