/**
 * 
 */
package edu.unicen.surfforecaster.server.domain.entity.forecaster.WW3DataManager;

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import edu.unicen.surfforecaster.server.domain.entity.forecaster.Point;

/**
 * @author esteban
 * 
 */
@Entity
public class ForecastPoints {
	/**
	 * Entity autogenerated id.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
	/**
	 * The latest forecast list
	 */
	@OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	private final Collection<Point> points = new ArrayList<Point>();

	/**
	 * The default constructor.
	 */
	public ForecastPoints() {
		// ORM purpose.
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * Add a point if not already exists.
	 * 
	 * @param pointToAdd
	 */
	public void addPoint(final Point pointToAdd) {
		if (!points.contains(pointToAdd)) {
			points.add(pointToAdd);
		}

	}

	/**
	 * @return
	 */
	public Collection<Point> getPoints() {
		return points;
	}
}
