/**
 * 
 */
package edu.unicen.surfforecaster.server.domain.entity.forecaster.WW3DataManager;

import java.util.Collection;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

import org.apache.commons.lang.Validate;

import edu.unicen.surfforecaster.server.domain.entity.forecaster.Forecast;

/**
 * An archive with past NOAA wave watch forecasts.
 * 
 * @author esteban
 * 
 */
@Entity
public class WW3ForecastArchive {
	/**
	 * Entity autogenerated id.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
	/**
	 * The latest forecast list
	 */
	@OneToOne(fetch = FetchType.EAGER)
	private Collection<Forecast> forecastArchive;

	/**
	 * The default constructor.
	 */
	public WW3ForecastArchive() {
		// ORM purpose.
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param forecast
	 */
	public void add(final Forecast forecast) {
		Validate.notNull(forecast);
		forecastArchive.add(forecast);

	}
}
