/**
 * 
 */
package edu.unicen.surfforecaster.server.domain.entity.forecaster.WW3DataManager;

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import org.apache.commons.lang.Validate;

import edu.unicen.surfforecaster.server.domain.entity.forecaster.Forecast;

/**
 * An archive with past NOAA wave watch forecasts.
 * 
 * @author esteban
 * 
 */
@Entity
public class ForecastArchive {
	/**
	 * Entity autogenerated id.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
	/**
	 * The latest forecast list
	 */
	@OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	private final Collection<Forecast> archive = new ArrayList<Forecast>();

	/**
	 * The default constructor.
	 */
	public ForecastArchive() {
		// ORM purpose.
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param forecast
	 */
	public void add(final Forecast forecast) {
		Validate.notNull(forecast);
		archive.add(forecast);

	}
}
