package edu.unicen.surfforecaster.gwt.client.utils;

import java.util.Arrays;
import java.util.HashMap;

public class TimeZones {
	
	private HashMap<String, Object> timeZones = null;
	private static TimeZones instance = null;
	
	public static TimeZones getInstance() {
        if (instance == null) {
            instance = new TimeZones();
        }
        return instance;
    }
	
	public TimeZones() {
		timeZones = new HashMap<String, Object>();
		timeZones.put("[UTC-12] UTC-12", "Etc/GMT-12");
		timeZones.put("[UTC-11] Pacific/Apia, WST", "Pacific/Apia");
		timeZones.put("[UTC-11] Pacific/Midway, SST", "Pacific/Midway");
		timeZones.put("[UTC-11] Pacific/Niue, NUT", "Pacific/Niue");
		timeZones.put("[UTC-11] Pacific/Pago_Pago, SST", "Pacific/Pago_Pago");
		timeZones.put("[UTC-11] Pacific/Samoa, SST", "Pacific/Samoa");
		timeZones.put("[UTC-11] US/Samoa, SST", "US/Samoa");
		timeZones.put("[UTC-11] UTC-11", "Etc/GMT-11");
		timeZones.put("[UTC-10] America/Adak, HAST (HADT)", "America/Adak");
		timeZones.put("[UTC-10] America/Atka, HAST (HADT)", "America/Atka");
		timeZones.put("[UTC-10] Pacific/Fakaofo, TKT", "Pacific/Fakaofo");
		timeZones.put("[UTC-10] Pacific/Honolulu, HST", "Pacific/Honolulu");
		timeZones.put("[UTC-10] Pacific/Johnston, HST", "Pacific/Johnston");
		timeZones.put("[UTC-10] Pacific/Rarotonga, CKT", "Pacific/Rarotonga");
		timeZones.put("[UTC-10] Pacific/Tahiti, TAHT", "Pacific/Tahiti");
		timeZones.put("[UTC-10] US/Aleutian, HAST (HADT)", "US/Aleutian");
		timeZones.put("[UTC-10] US/Hawaii, HST", "US/Hawaii");
		timeZones.put("[UTC-10] UTC-10", "Etc/GMT-10");
		timeZones.put("[UTC] Pacific/Marquesas, MART", "Pacific/Marquesas");
		timeZones.put("[UTC-9] America/Anchorage, AKST (AKDT)", "America/Anchorage");
		timeZones.put("[UTC-9] America/Juneau, AKST (AKDT)", "America/Juneau");
		timeZones.put("[UTC-9] America/Nome, AKST (AKDT)", "America/Nome");
		timeZones.put("[UTC-9] America/Yakutat, AKST (AKDT)", "America/Yakutat");
		timeZones.put("[UTC-9] Pacific/Gambier, GAMT", "Pacific/Gambier");
		timeZones.put("[UTC-9] US/Alaska, AKST (AKDT)", "US/Alaska");
		timeZones.put("[UTC-9] UTC-9", "Etc/GMT-9");
		timeZones.put("[UTC-8] America/Dawson, PST (PDT)", "America/Dawson");
		timeZones.put("[UTC-8] America/Ensenada, PST (PDT)", "America/Ensenada");
		timeZones.put("[UTC-8] America/Los_Angeles, PST (PDT)", "America/Los_Angeles");
		timeZones.put("[UTC-8] America/Tijuana, PST (PDT)", "America/Tijuana");
		timeZones.put("[UTC-8] America/Vancouver, PST (PDT)", "America/Vancouver");
		timeZones.put("[UTC-8] America/Whitehorse, PST (PDT)", "America/Whitehorse");
		timeZones.put("[UTC-8] Canada/Pacific, PST (PDT)", "Canada/Pacific");
		timeZones.put("[UTC-8] Canada/Yukon, PST (PDT)", "Canada/Yukon");
		timeZones.put("[UTC-8] Mexico/BajaNorte, PST (PDT)", "Mexico/BajaNorte");
		timeZones.put("[UTC-8] Pacific/Pitcairn, PST", "Pacific/Pitcairn");
		timeZones.put("[UTC-8] US/Pacific-New, PST (PDT)", "US/Pacific-New");
		timeZones.put("[UTC-8] US/Pacific, PST (PDT)", "US/Pacific");
		timeZones.put("[UTC-8] UTC-8", "Etc/GMT-8");
		timeZones.put("[UTC-7] America/Boise, MST (MDT)", "America/Boise");
		timeZones.put("[UTC-7] America/Cambridge_Bay, MST (MDT)", "America/Cambridge_Bay");
		timeZones.put("[UTC-7] America/Chihuahua, MST (MDT)", "America/Chihuahua");
		timeZones.put("[UTC-7] America/Dawson_Creek, MST", "America/Dawson_Creek");
		timeZones.put("[UTC-7] America/Denver, MST (MDT)", "America/Denver");
		timeZones.put("[UTC-7] America/Edmonton, MST (MDT)", "America/Edmonton");
		timeZones.put("[UTC-7] America/Hermosillo, MST", "America/Hermosillo");
		timeZones.put("[UTC-7] America/Inuvik, MST (MDT)", "America/Inuvik");
		timeZones.put("[UTC-7] America/Mazatlan, MST (MDT)", "America/Mazatlan");
		timeZones.put("[UTC-7] America/Phoenix, MST", "America/Phoenix");
		timeZones.put("[UTC-7] America/Shiprock, MST (MDT)", "America/Shiprock");
		timeZones.put("[UTC-7] America/Yellowknife, MST (MDT)", "America/Yellowknife");
		timeZones.put("[UTC-7] Canada/Mountain, MST (MDT)", "Canada/Mountain");
		timeZones.put("[UTC-7] Mexico/BajaSur, MST (MDT)", "Mexico/BajaSur");
		timeZones.put("[UTC-7] Navajo, MST (MDT)", "Navajo");
		timeZones.put("[UTC-7] US/Arizona, MST", "US/Arizona");
		timeZones.put("[UTC-7] US/Mountain, MST (MDT)", "US/Mountain");
		timeZones.put("[UTC-7] UTC-7", "Etc/GMT-7");
		timeZones.put("[UTC-6] America/Belize, CST", "America/Belize");
		timeZones.put("[UTC-6] America/Cancun, CST (CDT)", "America/Cancun");
		timeZones.put("[UTC-6] America/Chicago, CST (CDT)", "America/Chicago");
		timeZones.put("[UTC-6] America/Costa_Rica, CST", "America/Costa_Rica");
		timeZones.put("[UTC-6] America/El_Salvador, CST", "America/El_Salvador");
		timeZones.put("[UTC-6] America/Guatemala, CST", "America/Guatemala");
		timeZones.put("[UTC-6] America/Indiana/Knox, EST (CDT)", "America/Indiana/Knox");
		timeZones.put("[UTC-6] America/Indiana/Tell_City, CST (CDT)", "America/Indiana/Tell_City");
		timeZones.put("[UTC-6] America/Knox_IN, EST (CDT)", "America/Knox_IN");
		timeZones.put("[UTC-6] America/Managua, CST", "America/Managua");
		timeZones.put("[UTC-6] America/Menominee, CST (CDT)", "America/Menominee");
		timeZones.put("[UTC-6] America/Merida, CST (CDT)", "America/Merida");
		timeZones.put("[UTC-6] America/Mexico_City, CST (CDT)", "America/Mexico_City");
		timeZones.put("[UTC-6] America/Monterrey, CST (CDT)", "America/Monterrey");
		timeZones.put("[UTC-6] America/North_Dakota/Center, CST (CDT)", "America/North_Dakota/Center");
		timeZones.put("[UTC-6] America/North_Dakota/New_Salem, CST (CDT)", "America/North_Dakota/New_Salem");
		timeZones.put("[UTC-6] America/Rainy_River, CST (CDT)", "America/Rainy_River");
		timeZones.put("[UTC-6] America/Rankin_Inlet, EST (EDT)", "America/Rankin_Inlet");
		timeZones.put("[UTC-6] America/Regina, CST", "America/Regina");
		timeZones.put("[UTC-6] America/Swift_Current, CST", "America/Swift_Current");
		timeZones.put("[UTC-6] America/Tegucigalpa, CST ()", "America/Tegucigalpa");
		timeZones.put("[UTC-6] America/Winnipeg, CST (CDT)", "America/Winnipeg");
		timeZones.put("[UTC-6] Canada/Central, CST (CDT)", "Canada/Central");
		timeZones.put("[UTC-6] Canada/East-Saskatchewan, CST", "Canada/East-Saskatchewan");
		timeZones.put("[UTC-6] Canada/Saskatchewan, CST", "Canada/Saskatchewan");
		timeZones.put("[UTC-6] Chile/EasterIsland, EAST (EASST)", "Chile/EasterIsland");
		timeZones.put("[UTC-6] Mexico/General, CST (CDT)", "Mexico/General");
		timeZones.put("[UTC-6] Pacific/Easter, EAST (EASST)", "Pacific/Easter");
		timeZones.put("[UTC-6] Pacific/Galapagos, GALT", "Pacific/Galapagos");
		timeZones.put("[UTC-6] US/Central, CST (CDT)", "US/Central");
		timeZones.put("[UTC-6] US/Indiana-Starke, EST (CDT)", "US/Indiana-Starke");
		timeZones.put("[UTC-6] UTC-6", "Etc/GMT-6");
		timeZones.put("[UTC-5] America/Atikokan, EST ()", "America/Atikokan");
		timeZones.put("[UTC-5] America/Bogota, COT", "America/Bogota");
		timeZones.put("[UTC-5] America/Cayman, EST", "America/Cayman");
		timeZones.put("[UTC-5] America/Coral_Harbour, EST ()", "America/Coral_Harbour");
		timeZones.put("[UTC-5] America/Detroit, EST (EDT)", "America/Detroit");
		timeZones.put("[UTC-5] America/Eirunepe, ACT", "America/Eirunepe");
		timeZones.put("[UTC-5] America/Fort_Wayne, EST (EDT)", "America/Fort_Wayne");
		timeZones.put("[UTC-5] America/Grand_Turk, EST (EDT)", "America/Grand_Turk");
		timeZones.put("[UTC-5] America/Guayaquil, ECT", "America/Guayaquil");
		timeZones.put("[UTC-5] America/Havana, CST (CDT)", "America/Havana");
		timeZones.put("[UTC-5] America/Indiana/Indianapolis, EST (EDT)", "America/Indiana/Indianapolis");
		timeZones.put("[UTC-5] America/Indiana/Marengo, EST (EDT)", "America/Indiana/Marengo");
		timeZones.put("[UTC-5] America/Indiana/Petersburg, CST (CDT)", "America/Indiana/Petersburg");
		timeZones.put("[UTC-5] America/Indianapolis, EST (EDT)", "America/Indianapolis");
		timeZones.put("[UTC-5] America/Indiana/Vevay, EST (EDT)", "America/Indiana/Vevay");
		timeZones.put("[UTC-5] America/Indiana/Vincennes, CST (CDT)", "America/Indiana/Vincennes");
		timeZones.put("[UTC-5] America/Indiana/Winamac, EST (EDT)", "America/Indiana/Winamac");
		timeZones.put("[UTC-5] America/Iqaluit, EST (EDT)", "America/Iqaluit");
		timeZones.put("[UTC-5] America/Jamaica, EST", "America/Jamaica");
		timeZones.put("[UTC-5] America/Kentucky/Louisville, EST (EDT)", "America/Kentucky/Louisville");
		timeZones.put("[UTC-5] America/Kentucky/Monticello, EST (EDT)", "America/Kentucky/Monticello");
		timeZones.put("[UTC-5] America/Lima, PET", "America/Lima");
		timeZones.put("[UTC-5] America/Louisville, EST (EDT)", "America/Louisville");
		timeZones.put("[UTC-5] America/Montreal, EST (EDT)", "America/Montreal");
		timeZones.put("[UTC-5] America/Nassau, EST (EDT)", "America/Nassau");
		timeZones.put("[UTC-5] America/New_York, EST (EDT)", "America/New_York");
		timeZones.put("[UTC-5] America/Nipigon, EST (EDT)", "America/Nipigon");
		timeZones.put("[UTC-5] America/Panama, EST", "America/Panama");
		timeZones.put("[UTC-5] America/Pangnirtung, EST (EDT)", "America/Pangnirtung");
		timeZones.put("[UTC-5] America/Port-au-Prince, EST ()", "America/Port-au-Prince");
		timeZones.put("[UTC-5] America/Porto_Acre, ACT", "America/Porto_Acre");
		timeZones.put("[UTC-5] America/Resolute, EST ()", "America/Resolute");
		timeZones.put("[UTC-5] America/Rio_Branco, ACT", "America/Rio_Branco");
		timeZones.put("[UTC-5] America/Thunder_Bay, EST (EDT)", "America/Thunder_Bay");
		timeZones.put("[UTC-5] America/Toronto, EST (EDT)", "America/Toronto");
		timeZones.put("[UTC-5] Brazil/Acre, ACT", "Brazil/Acre");
		timeZones.put("[UTC-5] Canada/Eastern, EST (EDT)", "Canada/Eastern");
		timeZones.put("[UTC-5] Cuba, CST (CDT)", "Cuba");
		timeZones.put("[UTC-5] Jamaica, EST", "Jamaica");
		timeZones.put("[UTC-5] US/Eastern, EST (EDT)", "US/Eastern");
		timeZones.put("[UTC-5] US/East-Indiana, EST (EDT)", "US/East-Indiana");
		timeZones.put("[UTC-5] US/Michigan, EST (EDT)", "US/Michigan");
		timeZones.put("[UTC-5] UTC-5", "Etc/GMT-5");
		timeZones.put("[UTC] America/Caracas, VET", "America/Caracas");
		timeZones.put("[UTC-4] America/Anguilla, AST", "America/Anguilla");
		timeZones.put("[UTC-4] America/Antigua, AST", "America/Antigua");
		timeZones.put("[UTC-4] America/Aruba, AST", "America/Aruba");
		timeZones.put("[UTC-4] America/Asuncion, PYT (PYST)", "America/Asuncion");
		timeZones.put("[UTC-4] America/Barbados, AST", "America/Barbados");
		timeZones.put("[UTC-4] America/Blanc-Sablon, AST ()", "America/Blanc-Sablon");
		timeZones.put("[UTC-4] America/Boa_Vista, AMT", "America/Boa_Vista");
		timeZones.put("[UTC-4] America/Campo_Grande, AMT (AMST)", "America/Campo_Grande");
		timeZones.put("[UTC-4] America/Cuiaba, AMT (AMST)", "America/Cuiaba");
		timeZones.put("[UTC-4] America/Curacao, AST", "America/Curacao");
		timeZones.put("[UTC-4] America/Dominica, AST", "America/Dominica");
		timeZones.put("[UTC-4] America/Glace_Bay, AST (ADT)", "America/Glace_Bay");
		timeZones.put("[UTC-4] America/Goose_Bay, AST (ADT)", "America/Goose_Bay");
		timeZones.put("[UTC-4] America/Grenada, AST", "America/Grenada");
		timeZones.put("[UTC-4] America/Guadeloupe, AST", "America/Guadeloupe");
		timeZones.put("[UTC-4] America/Guyana, GYT", "America/Guyana");
		timeZones.put("[UTC-4] America/Halifax, AST (ADT)", "America/Halifax");
		timeZones.put("[UTC-4] America/La_Paz, BOT", "America/La_Paz");
		timeZones.put("[UTC-4] America/Manaus, AMT", "America/Manaus");
		timeZones.put("[UTC-4] America/Marigot, AST ()", "America/Marigot");
		timeZones.put("[UTC-4] America/Martinique, AST", "America/Martinique");
		timeZones.put("[UTC-4] America/Moncton, AST (ADT)", "America/Moncton");
		timeZones.put("[UTC-4] America/Montserrat, AST", "America/Montserrat");
		timeZones.put("[UTC-4] America/Port_of_Spain, AST", "America/Port_of_Spain");
		timeZones.put("[UTC-4] America/Porto_Velho, AMT", "America/Porto_Velho");
		timeZones.put("[UTC-4] America/Puerto_Rico, AST", "America/Puerto_Rico");
		timeZones.put("[UTC-4] America/Santiago, CLT (CLST)", "America/Santiago");
		timeZones.put("[UTC-4] America/Santo_Domingo, AST", "America/Santo_Domingo");
		timeZones.put("[UTC-4] America/St_Barthelemy, AST ()", "America/St_Barthelemy");
		timeZones.put("[UTC-4] America/St_Kitts, AST", "America/St_Kitts");
		timeZones.put("[UTC-4] America/St_Lucia, AST", "America/St_Lucia");
		timeZones.put("[UTC-4] America/St_Thomas, AST", "America/St_Thomas");
		timeZones.put("[UTC-4] America/St_Vincent, AST", "America/St_Vincent");
		timeZones.put("[UTC-4] America/Thule, AST (ADT)", "America/Thule");
		timeZones.put("[UTC-4] America/Tortola, AST", "America/Tortola");
		timeZones.put("[UTC-4] America/Virgin, AST", "America/Virgin");
		timeZones.put("[UTC-4] Antarctica/Palmer, CLT (CLST)", "Antarctica/Palmer");
		timeZones.put("[UTC-4] Atlantic/Bermuda, AST (ADT)", "Atlantic/Bermuda");
		timeZones.put("[UTC-4] Atlantic/Stanley, FKT (FKST)", "Atlantic/Stanley");
		timeZones.put("[UTC-4] Brazil/West, AMT", "Brazil/West");
		timeZones.put("[UTC-4] Canada/Atlantic, AST (ADT)", "Canada/Atlantic");
		timeZones.put("[UTC-4] Chile/Continental, CLT (CLST)", "Chile/Continental");
		timeZones.put("[UTC-4] UTC-4", "Etc/GMT-4");
		timeZones.put("[UTC] America/St_Johns, NST (NDT)", "America/St_Johns");
		timeZones.put("[UTC] Canada/Newfoundland, NST (NDT)", "Canada/Newfoundland");
		timeZones.put("[UTC-3] America/Araguaina, BRT ()", "America/Araguaina");
		timeZones.put("[UTC-3] America/Argentina/Buenos_Aires, ART (ARST)", "America/Argentina/Buenos_Aires");
		timeZones.put("[UTC-3] America/Argentina/Catamarca, ART (ARST)", "America/Argentina/Catamarca");
		timeZones.put("[UTC-3] America/Argentina/ComodRivadavia, ART (ARST)", "America/Argentina/ComodRivadavia");
		timeZones.put("[UTC-3] America/Argentina/Cordoba, ART (ARST)", "America/Argentina/Cordoba");
		timeZones.put("[UTC-3] America/Argentina/Jujuy, ART (ARST)", "America/Argentina/Jujuy");
		timeZones.put("[UTC-3] America/Argentina/La_Rioja, ART (ARST)", "America/Argentina/La_Rioja");
		timeZones.put("[UTC-3] America/Argentina/Mendoza, ART (ARST)", "America/Argentina/Mendoza");
		timeZones.put("[UTC-3] America/Argentina/Rio_Gallegos, ART (ARST)", "America/Argentina/Rio_Gallegos");
		timeZones.put("[UTC-3] America/Argentina/San_Juan, ART (ARST)", "America/Argentina/San_Juan");
		timeZones.put("[UTC-3] America/Argentina/Tucuman, ART (ARST)", "America/Argentina/Tucuman");
		timeZones.put("[UTC-3] America/Argentina/Ushuaia, ART (ARST)", "America/Argentina/Ushuaia");
		timeZones.put("[UTC-3] America/Bahia, BRT ()", "America/Bahia");
		timeZones.put("[UTC-3] America/Belem, BRT", "America/Belem");
		timeZones.put("[UTC-3] America/Buenos_Aires, ART (ARST)", "America/Buenos_Aires");
		timeZones.put("[UTC-3] America/Catamarca, ART (ARST)", "America/Catamarca");
		timeZones.put("[UTC-3] America/Cayenne, GFT", "America/Cayenne");
		timeZones.put("[UTC-3] America/Cordoba, ART (ARST)", "America/Cordoba");
		timeZones.put("[UTC-3] America/Fortaleza, BRT ()", "America/Fortaleza");
		timeZones.put("[UTC-3] America/Godthab, WGT (WGST)", "America/Godthab");
		timeZones.put("[UTC-3] America/Jujuy, ART (ARST)", "America/Jujuy");
		timeZones.put("[UTC-3] America/Maceio, BRT ()", "America/Maceio");
		timeZones.put("[UTC-3] America/Mendoza, ART (ARST)", "America/Mendoza");
		timeZones.put("[UTC-3] America/Miquelon, PMST (PMDT)", "America/Miquelon");
		timeZones.put("[UTC-3] America/Montevideo, UYT (UYST)", "America/Montevideo");
		timeZones.put("[UTC-3] America/Paramaribo, SRT", "America/Paramaribo");
		timeZones.put("[UTC-3] America/Recife, BRT ()", "America/Recife");
		timeZones.put("[UTC-3] America/Rosario, ART (ARST)", "America/Rosario");
		timeZones.put("[UTC-3] America/Sao_Paulo, BRT (BRST)", "America/Sao_Paulo");
		timeZones.put("[UTC-3] Antarctica/Rothera, ROTT ()", "Antarctica/Rothera");
		timeZones.put("[UTC-3] Brazil/East, BRT (BRST)", "Brazil/East");
		timeZones.put("[UTC-3] UTC-3", "Etc/GMT-3");
		timeZones.put("[UTC-2] America/Noronha, FNT", "America/Noronha");
		timeZones.put("[UTC-2] Atlantic/South_Georgia, GST", "Atlantic/South_Georgia");
		timeZones.put("[UTC-2] Brazil/DeNoronha, FNT", "Brazil/DeNoronha");
		timeZones.put("[UTC-2] UTC-2", "Etc/GMT-2");
		timeZones.put("[UTC-1] America/Scoresbysund, EGT (EGST)", "America/Scoresbysund");
		timeZones.put("[UTC-1] Atlantic/Azores, AZOT (AZOST)", "Atlantic/Azores");
		timeZones.put("[UTC-1] Atlantic/Cape_Verde, CVT", "Atlantic/Cape_Verde");
		timeZones.put("[UTC-1] UTC-1", "Etc/GMT-1");
		timeZones.put("[UTC] Africa/Abidjan, GMT", "Africa/Abidjan");
		timeZones.put("[UTC] Africa/Accra, GMT", "Africa/Accra");
		timeZones.put("[UTC] Africa/Bamako, GMT", "Africa/Bamako");
		timeZones.put("[UTC] Africa/Banjul, GMT", "Africa/Banjul");
		timeZones.put("[UTC] Africa/Bissau, GMT", "Africa/Bissau");
		timeZones.put("[UTC] Africa/Casablanca, WET", "Africa/Casablanca");
		timeZones.put("[UTC] Africa/Conakry, GMT", "Africa/Conakry");
		timeZones.put("[UTC] Africa/Dakar, GMT", "Africa/Dakar");
		timeZones.put("[UTC] Africa/El_Aaiun, WET", "Africa/El_Aaiun");
		timeZones.put("[UTC] Africa/Freetown, GMT", "Africa/Freetown");
		timeZones.put("[UTC] Africa/Lome, GMT", "Africa/Lome");
		timeZones.put("[UTC] Africa/Monrovia, GMT", "Africa/Monrovia");
		timeZones.put("[UTC] Africa/Nouakchott, GMT", "Africa/Nouakchott");
		timeZones.put("[UTC] Africa/Ouagadougou, GMT", "Africa/Ouagadougou");
		timeZones.put("[UTC] Africa/Sao_Tome, GMT", "Africa/Sao_Tome");
		timeZones.put("[UTC] Africa/Timbuktu, GMT", "Africa/Timbuktu");
		timeZones.put("[UTC] America/Danmarkshavn, GMT", "America/Danmarkshavn");
		timeZones.put("[UTC] Atlantic/Canary, WET (WEST)", "Atlantic/Canary");
		timeZones.put("[UTC] Atlantic/Faeroe, WET (WEST)", "Atlantic/Faeroe");
		timeZones.put("[UTC] Atlantic/Faroe, WET (WEST)", "Atlantic/Faroe");
		timeZones.put("[UTC] Atlantic/Madeira, WET (WEST)", "Atlantic/Madeira");
		timeZones.put("[UTC] Atlantic/Reykjavik, GMT", "Atlantic/Reykjavik");
		timeZones.put("[UTC] Atlantic/St_Helena, GMT", "Atlantic/St_Helena");
		timeZones.put("[UTC] Europe/Belfast, GMT (BST)", "Europe/Belfast");
		timeZones.put("[UTC] Europe/Dublin, GMT (IST)", "Europe/Dublin");
		timeZones.put("[UTC] Europe/Guernsey, GMT (BST)", "Europe/Guernsey");
		timeZones.put("[UTC] Europe/Isle_of_Man, GMT (BST)", "Europe/Isle_of_Man");
		timeZones.put("[UTC] Europe/Jersey, GMT (BST)", "Europe/Jersey");
		timeZones.put("[UTC] Europe/Lisbon, WET (WEST)", "Europe/Lisbon");
		timeZones.put("[UTC] Europe/London, GMT (BST)", "Europe/London");
		timeZones.put("[UTC] GB-Eire, GMT (BST)", "GB-Eire");
		timeZones.put("[UTC] Iceland, GMT", "Iceland");
		timeZones.put("[UTC] Portugal, WET (WEST)", "Portugal");
		timeZones.put("[UTC] UTC+0", "Etc/GMT+0");
		timeZones.put("[UTC+1] Africa/Algiers, CET", "Africa/Algiers");
		timeZones.put("[UTC+1] Africa/Bangui, WAT", "Africa/Bangui");
		timeZones.put("[UTC+1] Africa/Brazzaville, WAT", "Africa/Brazzaville");
		timeZones.put("[UTC+1] Africa/Ceuta, CET (CEST)", "Africa/Ceuta");
		timeZones.put("[UTC+1] Africa/Douala, WAT", "Africa/Douala");
		timeZones.put("[UTC+1] Africa/Kinshasa, WAT", "Africa/Kinshasa");
		timeZones.put("[UTC+1] Africa/Lagos, WAT", "Africa/Lagos");
		timeZones.put("[UTC+1] Africa/Libreville, WAT", "Africa/Libreville");
		timeZones.put("[UTC+1] Africa/Luanda, WAT", "Africa/Luanda");
		timeZones.put("[UTC+1] Africa/Malabo, WAT", "Africa/Malabo");
		timeZones.put("[UTC+1] Africa/Ndjamena, WAT", "Africa/Ndjamena");
		timeZones.put("[UTC+1] Africa/Niamey, WAT", "Africa/Niamey");
		timeZones.put("[UTC+1] Africa/Porto-Novo, WAT", "Africa/Porto-Novo");
		timeZones.put("[UTC+1] Africa/Tunis, CET (CEST)", "Africa/Tunis");
		timeZones.put("[UTC+1] Africa/Windhoek, WAT (WAST)", "Africa/Windhoek");
		timeZones.put("[UTC+1] Arctic/Longyearbyen, CET (CEST)", "Arctic/Longyearbyen");
		timeZones.put("[UTC+1] Atlantic/Jan_Mayen, EGT (EGST)", "Atlantic/Jan_Mayen");
		timeZones.put("[UTC+1] Europe/Amsterdam, CET (CEST)", "Europe/Amsterdam");
		timeZones.put("[UTC+1] Europe/Andorra, CET (CEST)", "Europe/Andorra");
		timeZones.put("[UTC+1] Europe/Belgrade, CET (CEST)", "Europe/Belgrade");
		timeZones.put("[UTC+1] Europe/Berlin, CET (CEST)", "Europe/Berlin");
		timeZones.put("[UTC+1] Europe/Bratislava, CET (CEST)", "Europe/Bratislava");
		timeZones.put("[UTC+1] Europe/Brussels, CET (CEST)", "Europe/Brussels");
		timeZones.put("[UTC+1] Europe/Budapest, CET (CEST)", "Europe/Budapest");
		timeZones.put("[UTC+1] Europe/Copenhagen, CET (CEST)", "Europe/Copenhagen");
		timeZones.put("[UTC+1] Europe/Gibraltar, CET (CEST)", "Europe/Gibraltar");
		timeZones.put("[UTC+1] Europe/Ljubljana, CET (CEST)", "Europe/Ljubljana");
		timeZones.put("[UTC+1] Europe/Luxembourg, CET (CEST)", "Europe/Luxembourg");
		timeZones.put("[UTC+1] Europe/Madrid, CET (CEST)", "Europe/Madrid");
		timeZones.put("[UTC+1] Europe/Malta, CET (CEST)", "Europe/Malta");
		timeZones.put("[UTC+1] Europe/Monaco, CET (CEST)", "Europe/Monaco");
		timeZones.put("[UTC+1] Europe/Oslo, CET (CEST)", "Europe/Oslo");
		timeZones.put("[UTC+1] Europe/Paris, CET (CEST)", "Europe/Paris");
		timeZones.put("[UTC+1] Europe/Podgorica, CET (CEST)", "Europe/Podgorica");
		timeZones.put("[UTC+1] Europe/Prague, CET (CEST)", "Europe/Prague");
		timeZones.put("[UTC+1] Europe/Rome, CET (CEST)", "Europe/Rome");
		timeZones.put("[UTC+1] Europe/San_Marino, CET (CEST)", "Europe/San_Marino");
		timeZones.put("[UTC+1] Europe/Sarajevo, CET (CEST)", "Europe/Sarajevo");
		timeZones.put("[UTC+1] Europe/Skopje, CET (CEST)", "Europe/Skopje");
		timeZones.put("[UTC+1] Europe/Stockholm, CET (CEST)", "Europe/Stockholm");
		timeZones.put("[UTC+1] Europe/Tirane, CET (CEST)", "Europe/Tirane");
		timeZones.put("[UTC+1] Europe/Vaduz, CET (CEST)", "Europe/Vaduz");
		timeZones.put("[UTC+1] Europe/Vatican, CET (CEST)", "Europe/Vatican");
		timeZones.put("[UTC+1] Europe/Vienna, CET (CEST)", "Europe/Vienna");
		timeZones.put("[UTC+1] Europe/Warsaw, CET (CEST)", "Europe/Warsaw");
		timeZones.put("[UTC+1] Europe/Zagreb, CET (CEST)", "Europe/Zagreb");
		timeZones.put("[UTC+1] Europe/Zurich, CET (CEST)", "Europe/Zurich");
		timeZones.put("[UTC+1] Poland, CET (CEST)", "Poland");
		timeZones.put("[UTC+1] UTC+1", "Etc/GMT+1");
		timeZones.put("[UTC+2] Africa/Blantyre, CAT", "Africa/Blantyre");
		timeZones.put("[UTC+2] Africa/Bujumbura, CAT", "Africa/Bujumbura");
		timeZones.put("[UTC+2] Africa/Cairo, EET (EEST)", "Africa/Cairo");
		timeZones.put("[UTC+2] Africa/Gaborone, CAT", "Africa/Gaborone");
		timeZones.put("[UTC+2] Africa/Harare, CAT", "Africa/Harare");
		timeZones.put("[UTC+2] Africa/Johannesburg, SAST", "Africa/Johannesburg");
		timeZones.put("[UTC+2] Africa/Kigali, CAT", "Africa/Kigali");
		timeZones.put("[UTC+2] Africa/Lubumbashi, CAT", "Africa/Lubumbashi");
		timeZones.put("[UTC+2] Africa/Lusaka, CAT", "Africa/Lusaka");
		timeZones.put("[UTC+2] Africa/Maputo, CAT", "Africa/Maputo");
		timeZones.put("[UTC+2] Africa/Maseru, SAST", "Africa/Maseru");
		timeZones.put("[UTC+2] Africa/Mbabane, SAST", "Africa/Mbabane");
		timeZones.put("[UTC+2] Africa/Tripoli, EET", "Africa/Tripoli");
		timeZones.put("[UTC+2] Asia/Amman, EET (EEST)", "Asia/Amman");
		timeZones.put("[UTC+2] Asia/Beirut, EET (EEST)", "Asia/Beirut");
		timeZones.put("[UTC+2] Asia/Damascus, EET (EEST)", "Asia/Damascus");
		timeZones.put("[UTC+2] Asia/Gaza, EET (EEST)", "Asia/Gaza");
		timeZones.put("[UTC+2] Asia/Istanbul, EET (EEST)", "Asia/Istanbul");
		timeZones.put("[UTC+2] Asia/Jerusalem, IST (IDT)", "Asia/Jerusalem");
		timeZones.put("[UTC+2] Asia/Nicosia, EET (EEST)", "Asia/Nicosia");
		timeZones.put("[UTC+2] Asia/Tel_Aviv, IST (IDT)", "Asia/Tel_Aviv");
		timeZones.put("[UTC+2] Egypt, EET (EEST)", "Egypt");
		timeZones.put("[UTC+2] Europe/Athens, EET (EEST)", "Europe/Athens");
		timeZones.put("[UTC+2] Europe/Bucharest, EET (EEST)", "Europe/Bucharest");
		timeZones.put("[UTC+2] Europe/Chisinau, EET (EEST)", "Europe/Chisinau");
		timeZones.put("[UTC+2] Europe/Helsinki, EET (EEST)", "Europe/Helsinki");
		timeZones.put("[UTC+2] Europe/Istanbul, EET (EEST)", "Europe/Istanbul");
		timeZones.put("[UTC+2] Europe/Kaliningrad, EET (EEST)", "Europe/Kaliningrad");
		timeZones.put("[UTC+2] Europe/Kiev, EET (EEST)", "Europe/Kiev");
		timeZones.put("[UTC+2] Europe/Mariehamn, EET (EEST)", "Europe/Mariehamn");
		timeZones.put("[UTC+2] Europe/Minsk, EET (EEST)", "Europe/Minsk");
		timeZones.put("[UTC+2] Europe/Nicosia, EET (EEST)", "Europe/Nicosia");
		timeZones.put("[UTC+2] Europe/Riga, EET (EEST)", "Europe/Riga");
		timeZones.put("[UTC+2] Europe/Simferopol, EET (EEST)", "Europe/Simferopol");
		timeZones.put("[UTC+2] Europe/Sofia, EET (EEST)", "Europe/Sofia");
		timeZones.put("[UTC+2] Europe/Tallinn, EET (EEST)", "Europe/Tallinn");
		timeZones.put("[UTC+2] Europe/Tiraspol, EET (EEST)", "Europe/Tiraspol");
		timeZones.put("[UTC+2] Europe/Uzhgorod, EET (EEST)", "Europe/Uzhgorod");
		timeZones.put("[UTC+2] Europe/Vilnius, EET (EEST)", "Europe/Vilnius");
		timeZones.put("[UTC+2] Europe/Zaporozhye, EET (EEST)", "Europe/Zaporozhye");
		timeZones.put("[UTC+2] Israel, IST (IDT)", "Israel");
		timeZones.put("[UTC+2] Libya, EET", "Libya");
		timeZones.put("[UTC+2] Turkey, EET (EEST)", "Turkey");
		timeZones.put("[UTC+2] UTC+2", "Etc/GMT+2");
		timeZones.put("[UTC+3] Africa/Addis_Ababa, EAT", "Africa/Addis_Ababa");
		timeZones.put("[UTC+3] Africa/Asmara, EAT ()", "Africa/Asmara");
		timeZones.put("[UTC+3] Africa/Asmera, EAT", "Africa/Asmera");
		timeZones.put("[UTC+3] Africa/Dar_es_Salaam, EAT", "Africa/Dar_es_Salaam");
		timeZones.put("[UTC+3] Africa/Djibouti, EAT", "Africa/Djibouti");
		timeZones.put("[UTC+3] Africa/Kampala, EAT", "Africa/Kampala");
		timeZones.put("[UTC+3] Africa/Khartoum, EAT", "Africa/Khartoum");
		timeZones.put("[UTC+3] Africa/Mogadishu, EAT", "Africa/Mogadishu");
		timeZones.put("[UTC+3] Africa/Nairobi, EAT", "Africa/Nairobi");
		timeZones.put("[UTC+3] Antarctica/Syowa, SYOT", "Antarctica/Syowa");
		timeZones.put("[UTC+3] Asia/Aden, AST", "Asia/Aden");
		timeZones.put("[UTC+3] Asia/Baghdad, AST (ADT)", "Asia/Baghdad");
		timeZones.put("[UTC+3] Asia/Bahrain, AST", "Asia/Bahrain");
		timeZones.put("[UTC+3] Asia/Kuwait, AST", "Asia/Kuwait");
		timeZones.put("[UTC+3] Asia/Qatar, AST", "Asia/Qatar");
		timeZones.put("[UTC+3] Asia/Riyadh, AST", "Asia/Riyadh");
		timeZones.put("[UTC+3] Europe/Moscow, MSK (MSD)", "Europe/Moscow");
		timeZones.put("[UTC+3] Europe/Volgograd, VOLT (VOLST)", "Europe/Volgograd");
		timeZones.put("[UTC+3] Indian/Antananarivo, EAT", "Indian/Antananarivo");
		timeZones.put("[UTC+3] Indian/Comoro, EAT", "Indian/Comoro");
		timeZones.put("[UTC+3] Indian/Mayotte, EAT", "Indian/Mayotte");
		timeZones.put("[UTC+3] UTC+3", "Etc/GMT+3");
		timeZones.put("[UTC+3.5] Asia/Tehran, IRT (IRDT)", "Asia/Tehran");
		timeZones.put("[UTC+3.5] Iran, IRT (IRDT)", "Iran");
		timeZones.put("[UTC+4] Asia/Baku, AZT (AZST)", "Asia/Baku");
		timeZones.put("[UTC+4] Asia/Dubai, GST", "Asia/Dubai");
		timeZones.put("[UTC+4] Asia/Muscat, GST", "Asia/Muscat");
		timeZones.put("[UTC+4] Asia/Tbilisi, GET ()", "Asia/Tbilisi");
		timeZones.put("[UTC+4] Asia/Yerevan, AMT (AMST)", "Asia/Yerevan");
		timeZones.put("[UTC+4] Europe/Samara, SAMT (SAMST)", "Europe/Samara");
		timeZones.put("[UTC+4] Indian/Mahe, SCT", "Indian/Mahe");
		timeZones.put("[UTC+4] Indian/Mauritius, MUT", "Indian/Mauritius");
		timeZones.put("[UTC+4] Indian/Reunion, RET", "Indian/Reunion");
		timeZones.put("[UTC+4] UTC+4", "Etc/GMT+4");
		timeZones.put("[UTC+4.5] Asia/Kabul, AFT", "Asia/Kabul");
		timeZones.put("[UTC+5] Asia/Aqtau, AQTT ()", "Asia/Aqtau");
		timeZones.put("[UTC+5] Asia/Aqtobe, AQTT ()", "Asia/Aqtobe");
		timeZones.put("[UTC+5] Asia/Ashgabat, TMT", "Asia/Ashgabat");
		timeZones.put("[UTC+5] Asia/Ashkhabad, TMT", "Asia/Ashkhabad");
		timeZones.put("[UTC+5] Asia/Dushanbe, TJT", "Asia/Dushanbe");
		timeZones.put("[UTC+5] Asia/Karachi, PKT", "Asia/Karachi");
		timeZones.put("[UTC+5] Asia/Oral, ORAT ()", "Asia/Oral");
		timeZones.put("[UTC+5] Asia/Samarkand, TMT", "Asia/Samarkand");
		timeZones.put("[UTC+5] Asia/Tashkent, UZT", "Asia/Tashkent");
		timeZones.put("[UTC+5] Asia/Yekaterinburg, YEKT (YEKST)", "Asia/Yekaterinburg");
		timeZones.put("[UTC+5] Indian/Kerguelen, TFT", "Indian/Kerguelen");
		timeZones.put("[UTC+5] Indian/Maldives, MVT", "Indian/Maldives");
		timeZones.put("[UTC+5] UTC+5", "Etc/GMT+5");
		timeZones.put("[UTC+5.5] Asia/Calcutta, IST", "Asia/Calcutta");
		timeZones.put("[UTC+5.5] Asia/Colombo, LKT", "Asia/Colombo");
		timeZones.put("[UTC+5.8] Asia/Katmandu, NPT", "Asia/Katmandu");
		timeZones.put("[UTC+6] Antarctica/Mawson, MAWT", "Antarctica/Mawson");
		timeZones.put("[UTC+6] Antarctica/Vostok, VOST", "Antarctica/Vostok");
		timeZones.put("[UTC+6] Asia/Almaty, ALMT ()", "Asia/Almaty");
		timeZones.put("[UTC+6] Asia/Bishkek, KGT ()", "Asia/Bishkek");
		timeZones.put("[UTC+6] Asia/Dacca, BDT", "Asia/Dacca");
		timeZones.put("[UTC+6] Asia/Dhaka, BDT", "Asia/Dhaka");
		timeZones.put("[UTC+6] Asia/Novosibirsk, NOVT (NOVST)", "Asia/Novosibirsk");
		timeZones.put("[UTC+6] Asia/Omsk, OMST (OMSST)", "Asia/Omsk");
		timeZones.put("[UTC+6] Asia/Qyzylorda, QYZT ()", "Asia/Qyzylorda");
		timeZones.put("[UTC+6] Asia/Thimbu, BTT", "Asia/Thimbu");
		timeZones.put("[UTC+6] Asia/Thimphu, BTT", "Asia/Thimphu");
		timeZones.put("[UTC+6] Indian/Chagos, IOT", "Indian/Chagos");
		timeZones.put("[UTC+6] UTC+6", "Etc/GMT+6");
		timeZones.put("[UTC+6.5] Asia/Rangoon, MMT", "Asia/Rangoon");
		timeZones.put("[UTC+6.5] Indian/Cocos, CCT", "Indian/Cocos");
		timeZones.put("[UTC+7] Antarctica/Davis, DAVT", "Antarctica/Davis");
		timeZones.put("[UTC+7] Asia/Bangkok, ICT", "Asia/Bangkok");
		timeZones.put("[UTC+7] Asia/Hovd, HOVT ()", "Asia/Hovd");
		timeZones.put("[UTC+7] Asia/Jakarta, WIT", "Asia/Jakarta");
		timeZones.put("[UTC+7] Asia/Krasnoyarsk, KRAT (KRAST)", "Asia/Krasnoyarsk");
		timeZones.put("[UTC+7] Asia/Phnom_Penh, ICT", "Asia/Phnom_Penh");
		timeZones.put("[UTC+7] Asia/Pontianak, WIT", "Asia/Pontianak");
		timeZones.put("[UTC+7] Asia/Saigon, ICT", "Asia/Saigon");
		timeZones.put("[UTC+7] Asia/Vientiane, ICT", "Asia/Vientiane");
		timeZones.put("[UTC+7] Indian/Christmas, CXT", "Indian/Christmas");
		timeZones.put("[UTC+7] UTC+7", "Etc/GMT+7");
		timeZones.put("[UTC+8] Antarctica/Casey, WST", "Antarctica/Casey");
		timeZones.put("[UTC+8] Asia/Brunei, BNT", "Asia/Brunei");
		timeZones.put("[UTC+8] Asia/Chongqing, CST", "Asia/Chongqing");
		timeZones.put("[UTC+8] Asia/Chungking, CST", "Asia/Chungking");
		timeZones.put("[UTC+8] Asia/Harbin, CST", "Asia/Harbin");
		timeZones.put("[UTC+8] Asia/Hong_Kong, HKT", "Asia/Hong_Kong");
		timeZones.put("[UTC+8] Asia/Irkutsk, IRKT (IRKST)", "Asia/Irkutsk");
		timeZones.put("[UTC+8] Asia/Kashgar, CST", "Asia/Kashgar");
		timeZones.put("[UTC+8] Asia/Kuala_Lumpur, MYT", "Asia/Kuala_Lumpur");
		timeZones.put("[UTC+8] Asia/Kuching, MYT", "Asia/Kuching");
		timeZones.put("[UTC+8] Asia/Macao, CST", "Asia/Macao");
		timeZones.put("[UTC+8] Asia/Macau, CST ()", "Asia/Macau");
		timeZones.put("[UTC+8] Asia/Makassar, CIT ()", "Asia/Makassar");
		timeZones.put("[UTC+8] Asia/Manila, PHT", "Asia/Manila");
		timeZones.put("[UTC+8] Asia/Shanghai, CST", "Asia/Shanghai");
		timeZones.put("[UTC+8] Asia/Singapore, SGT", "Asia/Singapore");
		timeZones.put("[UTC+8] Asia/Taipei, CST", "Asia/Taipei");
		timeZones.put("[UTC+8] Asia/Ujung_Pandang, CIT", "Asia/Ujung_Pandang");
		timeZones.put("[UTC+8] Asia/Ulaanbaatar, ULAT ()", "Asia/Ulaanbaatar");
		timeZones.put("[UTC+8] Asia/Ulan_Bator, ULAT ()", "Asia/Ulan_Bator");
		timeZones.put("[UTC+8] Asia/Urumqi, CST", "Asia/Urumqi");
		timeZones.put("[UTC+8] Australia/Perth, WST (WST)", "Australia/Perth");
		timeZones.put("[UTC+8] Australia/West, WST (WST)", "Australia/West");
		timeZones.put("[UTC+8] Hongkong, HKT", "Hongkong");
		timeZones.put("[UTC+8] Singapore, SGT", "Singapore");
		timeZones.put("[UTC+8] UTC+8", "Etc/GMT+8");
		timeZones.put("[UTC+8.8] Australia/Eucla, CWST (CWST)", "Australia/Eucla");
		timeZones.put("[UTC+9] Asia/Choibalsan, CHOT ()", "Asia/Choibalsan");
		timeZones.put("[UTC+9] Asia/Dili, TPT", "Asia/Dili");
		timeZones.put("[UTC+9] Asia/Jayapura, EIT", "Asia/Jayapura");
		timeZones.put("[UTC+9] Asia/Pyongyang, KST", "Asia/Pyongyang");
		timeZones.put("[UTC+9] Asia/Seoul, KST", "Asia/Seoul");
		timeZones.put("[UTC+9] Asia/Tokyo, JST", "Asia/Tokyo");
		timeZones.put("[UTC+9] Asia/Yakutsk, YAKT (YAKST)", "Asia/Yakutsk");
		timeZones.put("[UTC+9] Japan, JST", "Japan");
		timeZones.put("[UTC+9] Pacific/Palau, PWT", "Pacific/Palau");
		timeZones.put("[UTC+9] UTC+9", "Etc/GMT+9");
		timeZones.put("[UTC+9.5] Australia/Adelaide, CST (CST)", "Australia/Adelaide");
		timeZones.put("[UTC+9.5] Australia/Broken_Hill, CST (CST)", "Australia/Broken_Hill");
		timeZones.put("[UTC+9.5] Australia/Darwin, CST", "Australia/Darwin");
		timeZones.put("[UTC+9.5] Australia/North, CST", "Australia/North");
		timeZones.put("[UTC+9.5] Australia/South, CST (CST)", "Australia/South");
		timeZones.put("[UTC+9.5] Australia/Yancowinna, CST (CST)", "Australia/Yancowinna");
		timeZones.put("[UTC+10] Antarctica/DumontDUrville, DDUT", "Antarctica/DumontDUrville");
		timeZones.put("[UTC+10] Asia/Sakhalin, SAKT (SAKST)", "Asia/Sakhalin");
		timeZones.put("[UTC+10] Asia/Vladivostok, VLAT (VLAST)", "Asia/Vladivostok");
		timeZones.put("[UTC+10] Australia/ACT, EST (EST)", "Australia/ACT");
		timeZones.put("[UTC+10] Australia/Brisbane, EST", "Australia/Brisbane");
		timeZones.put("[UTC+10] Australia/Canberra, EST (EST)", "Australia/Canberra");
		timeZones.put("[UTC+10] Australia/Currie, EST (EST)", "Australia/Currie");
		timeZones.put("[UTC+10] Australia/Hobart, EST (EST)", "Australia/Hobart");
		timeZones.put("[UTC+10] Australia/Lindeman, EST", "Australia/Lindeman");
		timeZones.put("[UTC+10] Australia/Melbourne, EST (EST)", "Australia/Melbourne");
		timeZones.put("[UTC+10] Australia/NSW, EST (EST)", "Australia/NSW");
		timeZones.put("[UTC+10] Australia/Queensland, EST", "Australia/Queensland");
		timeZones.put("[UTC+10] Australia/Sydney, EST (EST)", "Australia/Sydney");
		timeZones.put("[UTC+10] Australia/Tasmania, EST (EST)", "Australia/Tasmania");
		timeZones.put("[UTC+10] Australia/Victoria, EST (EST)", "Australia/Victoria");
		timeZones.put("[UTC+10] Pacific/Guam, ChST", "Pacific/Guam");
		timeZones.put("[UTC+10] Pacific/Port_Moresby, PGT", "Pacific/Port_Moresby");
		timeZones.put("[UTC+10] Pacific/Saipan, ChST", "Pacific/Saipan");
		timeZones.put("[UTC+10] Pacific/Truk, TRUT", "Pacific/Truk");
		timeZones.put("[UTC+10] Pacific/Yap, YAPT", "Pacific/Yap");
		timeZones.put("[UTC+10] UTC+10", "Etc/GMT+10");
		timeZones.put("[UTC+10.5] Australia/LHI, LHST (LHST)", "Australia/LHI");
		timeZones.put("[UTC+10.5] Australia/Lord_Howe, LHST (LHST)", "Australia/Lord_Howe");
		timeZones.put("[UTC+11] Asia/Magadan, MAGT (MAGST)", "Asia/Magadan");
		timeZones.put("[UTC+11] Pacific/Efate, VUT", "Pacific/Efate");
		timeZones.put("[UTC+11] Pacific/Guadalcanal, SBT", "Pacific/Guadalcanal");
		timeZones.put("[UTC+11] Pacific/Kosrae, KOST", "Pacific/Kosrae");
		timeZones.put("[UTC+11] Pacific/Noumea, NCT", "Pacific/Noumea");
		timeZones.put("[UTC+11] Pacific/Ponape, PONT", "Pacific/Ponape");
		timeZones.put("[UTC+11] UTC+11", "Etc/GMT+11");
		timeZones.put("[UTC+11.5] Pacific/Norfolk, NFT", "Pacific/Norfolk");
		timeZones.put("[UTC+12] Antarctica/McMurdo, NZST (NZDT)", "Antarctica/McMurdo");
		timeZones.put("[UTC+12] Antarctica/South_Pole, NZST (NZDT)", "Antarctica/South_Pole");
		timeZones.put("[UTC+12] Asia/Anadyr, ANAT (ANAST)", "Asia/Anadyr");
		timeZones.put("[UTC+12] Asia/Kamchatka, PETT (PETST)", "Asia/Kamchatka");
		timeZones.put("[UTC+12] Pacific/Auckland, NZST (NZDT)", "Pacific/Auckland");
		timeZones.put("[UTC+12] Pacific/Fiji, FJT", "Pacific/Fiji");
		timeZones.put("[UTC+12] Pacific/Funafuti, TVT", "Pacific/Funafuti");
		timeZones.put("[UTC+12] Pacific/Kwajalein, MHT", "Pacific/Kwajalein");
		timeZones.put("[UTC+12] Pacific/Majuro, MHT", "Pacific/Majuro");
		timeZones.put("[UTC+12] Pacific/Nauru, NRT", "Pacific/Nauru");
		timeZones.put("[UTC+12] Pacific/Tarawa, GILT", "Pacific/Tarawa");
		timeZones.put("[UTC+12] Pacific/Wake, WAKT", "Pacific/Wake");
		timeZones.put("[UTC+12] Pacific/Wallis, WFT", "Pacific/Wallis");
		timeZones.put("[UTC+12] UTC+12", "Etc/GMT+12");
		timeZones.put("[UTC+12.8] Pacific/Chatham, CHAST (CHADT)", "Pacific/Chatham");
		timeZones.put("[UTC+13] Pacific/Enderbury, PHOT", "Pacific/Enderbury");
		timeZones.put("[UTC+13] Pacific/Tongatapu, TOT", "Pacific/Tongatapu");
		timeZones.put("[UTC+13] UTC+13", "Etc/GMT+13");
		timeZones.put("[UTC+14] Pacific/Kiritimati, LINT", "Pacific/Kiritimati");
		timeZones.put("[UTC+14] UTC+14", "Etc/GMT+14");
		
		//Add an item with and array of keys ordered by key name
		Object[] keys = timeZones.keySet().toArray();
		Arrays.sort(keys);
		timeZones.put("orderedKeys", keys);
	}
	
	public HashMap<String, Object> getTimeZones(){
		return this.timeZones;
	}
}
